output_queue_size: 1

cloud_filter_chain:
  - name: CropBoxFilter
    type: oxin_filters/CropBoxFilter
    params:
      active: True
      input_frame: "base_footprint"
      keep_organized: False
      negative: False
      #user_filter_value: 5
      min_x: -2.0
      max_x: 8.0
      min_y: -3
      max_y: 3
      min_z: -2
      max_z: 3

  - name: VoxelGridFilter
    type: oxin_filters/VoxelGridFilter
    params:
      active: True
      leaf_size_x: 0.1
      leaf_size_y: 0.2
      leaf_size_z: 0.1
      min_points_per_voxel: 1
      downsample_all_data: True
      filter_field_name: "z"
      filter_limit_min: -1
      filter_limit_max: 3
      negative: False

  - name: RadiusOutlierRemovalFilter
    type: oxin_filters/RadiusOutlierRemovalFilter
    params:
      active: True
      min_neighbors: 2
      radius_search: 0.1

  # - name: ExtractPlane
  #   type: oxin_filters/SacSegmentationExtractFilter
  #   params:
  #     active: True
  #     input_frame: "base_link"
  #     output_frame: "base_link"
  #     model_type: 16
  #     method_type: 0
  #     axis_x: 0
  #     axis_y: 0
  #     axis_z: 1
  #     eps_angle: 0.15
  #     distance_threshold: 0.01
  #     negative: True
  #     optimize_coefficents: True

